/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SermonsRouteImport } from './routes/sermons'
import { Route as SalvationRouteImport } from './routes/salvation'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as MinistriesRouteImport } from './routes/ministries'
import { Route as MediaRouteImport } from './routes/media'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CampsRouteImport } from './routes/camps'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as READMERouteImport } from './routes/README'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MinistriesMyfRouteImport } from './routes/ministries.myf'
import { Route as MinistriesMyaRouteImport } from './routes/ministries.mya'
import { Route as MinistriesCampusRouteImport } from './routes/ministries.campus'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSermonsRouteImport } from './routes/admin.sermons'
import { Route as AdminResourcesRouteImport } from './routes/admin.resources'
import { Route as AdminMinistriesRouteImport } from './routes/admin.ministries'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as SitemapRouteImport } from './routes/sitemap.'

const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SermonsRoute = SermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => rootRouteImport,
} as any)
const SalvationRoute = SalvationRouteImport.update({
  id: '/salvation',
  path: '/salvation',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesRoute = MinistriesRouteImport.update({
  id: '/ministries',
  path: '/ministries',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CampsRoute = CampsRouteImport.update({
  id: '/camps',
  path: '/camps',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const READMERoute = READMERouteImport.update({
  id: '/README',
  path: '/README',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MinistriesMyfRoute = MinistriesMyfRouteImport.update({
  id: '/myf',
  path: '/myf',
  getParentRoute: () => MinistriesRoute,
} as any)
const MinistriesMyaRoute = MinistriesMyaRouteImport.update({
  id: '/mya',
  path: '/mya',
  getParentRoute: () => MinistriesRoute,
} as any)
const MinistriesCampusRoute = MinistriesCampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => MinistriesRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSermonsRoute = AdminSermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMinistriesRoute = AdminMinistriesRouteImport.update({
  id: '/ministries',
  path: '/ministries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap/',
  path: '/sitemap/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/README': typeof READMERoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/camps': typeof CampsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/media': typeof MediaRoute
  '/ministries': typeof MinistriesRouteWithChildren
  '/prayer': typeof PrayerRoute
  '/salvation': typeof SalvationRoute
  '/sermons': typeof SermonsRoute
  '/stories': typeof StoriesRoute
  '/visit': typeof VisitRoute
  '/sitemap/': typeof SitemapRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/ministries': typeof AdminMinistriesRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/sermons': typeof AdminSermonsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ministries/campus': typeof MinistriesCampusRoute
  '/ministries/mya': typeof MinistriesMyaRoute
  '/ministries/myf': typeof MinistriesMyfRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/README': typeof READMERoute
  '/about': typeof AboutRoute
  '/camps': typeof CampsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/media': typeof MediaRoute
  '/ministries': typeof MinistriesRouteWithChildren
  '/prayer': typeof PrayerRoute
  '/salvation': typeof SalvationRoute
  '/sermons': typeof SermonsRoute
  '/stories': typeof StoriesRoute
  '/visit': typeof VisitRoute
  '/sitemap': typeof SitemapRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/ministries': typeof AdminMinistriesRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/sermons': typeof AdminSermonsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ministries/campus': typeof MinistriesCampusRoute
  '/ministries/mya': typeof MinistriesMyaRoute
  '/ministries/myf': typeof MinistriesMyfRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/README': typeof READMERoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/camps': typeof CampsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/media': typeof MediaRoute
  '/ministries': typeof MinistriesRouteWithChildren
  '/prayer': typeof PrayerRoute
  '/salvation': typeof SalvationRoute
  '/sermons': typeof SermonsRoute
  '/stories': typeof StoriesRoute
  '/visit': typeof VisitRoute
  '/sitemap/': typeof SitemapRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/ministries': typeof AdminMinistriesRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/sermons': typeof AdminSermonsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ministries/campus': typeof MinistriesCampusRoute
  '/ministries/mya': typeof MinistriesMyaRoute
  '/ministries/myf': typeof MinistriesMyfRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/README'
    | '/about'
    | '/admin'
    | '/camps'
    | '/contact'
    | '/events'
    | '/media'
    | '/ministries'
    | '/prayer'
    | '/salvation'
    | '/sermons'
    | '/stories'
    | '/visit'
    | '/sitemap/'
    | '/admin/events'
    | '/admin/media'
    | '/admin/ministries'
    | '/admin/resources'
    | '/admin/sermons'
    | '/admin/users'
    | '/ministries/campus'
    | '/ministries/mya'
    | '/ministries/myf'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/README'
    | '/about'
    | '/camps'
    | '/contact'
    | '/events'
    | '/media'
    | '/ministries'
    | '/prayer'
    | '/salvation'
    | '/sermons'
    | '/stories'
    | '/visit'
    | '/sitemap'
    | '/admin/events'
    | '/admin/media'
    | '/admin/ministries'
    | '/admin/resources'
    | '/admin/sermons'
    | '/admin/users'
    | '/ministries/campus'
    | '/ministries/mya'
    | '/ministries/myf'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/README'
    | '/about'
    | '/admin'
    | '/camps'
    | '/contact'
    | '/events'
    | '/media'
    | '/ministries'
    | '/prayer'
    | '/salvation'
    | '/sermons'
    | '/stories'
    | '/visit'
    | '/sitemap/'
    | '/admin/events'
    | '/admin/media'
    | '/admin/ministries'
    | '/admin/resources'
    | '/admin/sermons'
    | '/admin/users'
    | '/ministries/campus'
    | '/ministries/mya'
    | '/ministries/myf'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  READMERoute: typeof READMERoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CampsRoute: typeof CampsRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  MediaRoute: typeof MediaRoute
  MinistriesRoute: typeof MinistriesRouteWithChildren
  PrayerRoute: typeof PrayerRoute
  SalvationRoute: typeof SalvationRoute
  SermonsRoute: typeof SermonsRoute
  StoriesRoute: typeof StoriesRoute
  VisitRoute: typeof VisitRoute
  SitemapRoute: typeof SitemapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sermons': {
      id: '/sermons'
      path: '/sermons'
      fullPath: '/sermons'
      preLoaderRoute: typeof SermonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salvation': {
      id: '/salvation'
      path: '/salvation'
      fullPath: '/salvation'
      preLoaderRoute: typeof SalvationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries': {
      id: '/ministries'
      path: '/ministries'
      fullPath: '/ministries'
      preLoaderRoute: typeof MinistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camps': {
      id: '/camps'
      path: '/camps'
      fullPath: '/camps'
      preLoaderRoute: typeof CampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/README': {
      id: '/README'
      path: '/README'
      fullPath: '/README'
      preLoaderRoute: typeof READMERouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ministries/myf': {
      id: '/ministries/myf'
      path: '/myf'
      fullPath: '/ministries/myf'
      preLoaderRoute: typeof MinistriesMyfRouteImport
      parentRoute: typeof MinistriesRoute
    }
    '/ministries/mya': {
      id: '/ministries/mya'
      path: '/mya'
      fullPath: '/ministries/mya'
      preLoaderRoute: typeof MinistriesMyaRouteImport
      parentRoute: typeof MinistriesRoute
    }
    '/ministries/campus': {
      id: '/ministries/campus'
      path: '/campus'
      fullPath: '/ministries/campus'
      preLoaderRoute: typeof MinistriesCampusRouteImport
      parentRoute: typeof MinistriesRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sermons': {
      id: '/admin/sermons'
      path: '/sermons'
      fullPath: '/admin/sermons'
      preLoaderRoute: typeof AdminSermonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ministries': {
      id: '/admin/ministries'
      path: '/ministries'
      fullPath: '/admin/ministries'
      preLoaderRoute: typeof AdminMinistriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sitemap/': {
      id: '/sitemap/'
      path: '/sitemap'
      fullPath: '/sitemap/'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminEventsRoute: typeof AdminEventsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMinistriesRoute: typeof AdminMinistriesRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminSermonsRoute: typeof AdminSermonsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventsRoute: AdminEventsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMinistriesRoute: AdminMinistriesRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminSermonsRoute: AdminSermonsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MinistriesRouteChildren {
  MinistriesCampusRoute: typeof MinistriesCampusRoute
  MinistriesMyaRoute: typeof MinistriesMyaRoute
  MinistriesMyfRoute: typeof MinistriesMyfRoute
}

const MinistriesRouteChildren: MinistriesRouteChildren = {
  MinistriesCampusRoute: MinistriesCampusRoute,
  MinistriesMyaRoute: MinistriesMyaRoute,
  MinistriesMyfRoute: MinistriesMyfRoute,
}

const MinistriesRouteWithChildren = MinistriesRoute._addFileChildren(
  MinistriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  READMERoute: READMERoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CampsRoute: CampsRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  MediaRoute: MediaRoute,
  MinistriesRoute: MinistriesRouteWithChildren,
  PrayerRoute: PrayerRoute,
  SalvationRoute: SalvationRoute,
  SermonsRoute: SermonsRoute,
  StoriesRoute: StoriesRoute,
  VisitRoute: VisitRoute,
  SitemapRoute: SitemapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
