/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SermonsRouteImport } from './routes/sermons'
import { Route as SalvationRouteImport } from './routes/salvation'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as MediaRouteImport } from './routes/media'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CampsRouteImport } from './routes/camps'
import { Route as AboutRouteImport } from './routes/about'
import { Route as READMERouteImport } from './routes/README'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MinistriesMyfRouteImport } from './routes/ministries.myf'
import { Route as MinistriesMyaRouteImport } from './routes/ministries.mya'
import { Route as MinistriesCampusRouteImport } from './routes/ministries.campus'
import { Route as SitemapRouteImport } from './routes/sitemap.'

const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SermonsRoute = SermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => rootRouteImport,
} as any)
const SalvationRoute = SalvationRouteImport.update({
  id: '/salvation',
  path: '/salvation',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CampsRoute = CampsRouteImport.update({
  id: '/camps',
  path: '/camps',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const READMERoute = READMERouteImport.update({
  id: '/README',
  path: '/README',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesMyfRoute = MinistriesMyfRouteImport.update({
  id: '/ministries/myf',
  path: '/ministries/myf',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesMyaRoute = MinistriesMyaRouteImport.update({
  id: '/ministries/mya',
  path: '/ministries/mya',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesCampusRoute = MinistriesCampusRouteImport.update({
  id: '/ministries/campus',
  path: '/ministries/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap/',
  path: '/sitemap/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/README': typeof READMERoute
  '/about': typeof AboutRoute
  '/camps': typeof CampsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/media': typeof MediaRoute
  '/prayer': typeof PrayerRoute
  '/salvation': typeof SalvationRoute
  '/sermons': typeof SermonsRoute
  '/stories': typeof StoriesRoute
  '/visit': typeof VisitRoute
  '/sitemap/': typeof SitemapRoute
  '/ministries/campus': typeof MinistriesCampusRoute
  '/ministries/mya': typeof MinistriesMyaRoute
  '/ministries/myf': typeof MinistriesMyfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/README': typeof READMERoute
  '/about': typeof AboutRoute
  '/camps': typeof CampsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/media': typeof MediaRoute
  '/prayer': typeof PrayerRoute
  '/salvation': typeof SalvationRoute
  '/sermons': typeof SermonsRoute
  '/stories': typeof StoriesRoute
  '/visit': typeof VisitRoute
  '/sitemap': typeof SitemapRoute
  '/ministries/campus': typeof MinistriesCampusRoute
  '/ministries/mya': typeof MinistriesMyaRoute
  '/ministries/myf': typeof MinistriesMyfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/README': typeof READMERoute
  '/about': typeof AboutRoute
  '/camps': typeof CampsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/media': typeof MediaRoute
  '/prayer': typeof PrayerRoute
  '/salvation': typeof SalvationRoute
  '/sermons': typeof SermonsRoute
  '/stories': typeof StoriesRoute
  '/visit': typeof VisitRoute
  '/sitemap/': typeof SitemapRoute
  '/ministries/campus': typeof MinistriesCampusRoute
  '/ministries/mya': typeof MinistriesMyaRoute
  '/ministries/myf': typeof MinistriesMyfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/README'
    | '/about'
    | '/camps'
    | '/contact'
    | '/events'
    | '/media'
    | '/prayer'
    | '/salvation'
    | '/sermons'
    | '/stories'
    | '/visit'
    | '/sitemap/'
    | '/ministries/campus'
    | '/ministries/mya'
    | '/ministries/myf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/README'
    | '/about'
    | '/camps'
    | '/contact'
    | '/events'
    | '/media'
    | '/prayer'
    | '/salvation'
    | '/sermons'
    | '/stories'
    | '/visit'
    | '/sitemap'
    | '/ministries/campus'
    | '/ministries/mya'
    | '/ministries/myf'
  id:
    | '__root__'
    | '/'
    | '/README'
    | '/about'
    | '/camps'
    | '/contact'
    | '/events'
    | '/media'
    | '/prayer'
    | '/salvation'
    | '/sermons'
    | '/stories'
    | '/visit'
    | '/sitemap/'
    | '/ministries/campus'
    | '/ministries/mya'
    | '/ministries/myf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  READMERoute: typeof READMERoute
  AboutRoute: typeof AboutRoute
  CampsRoute: typeof CampsRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  MediaRoute: typeof MediaRoute
  PrayerRoute: typeof PrayerRoute
  SalvationRoute: typeof SalvationRoute
  SermonsRoute: typeof SermonsRoute
  StoriesRoute: typeof StoriesRoute
  VisitRoute: typeof VisitRoute
  SitemapRoute: typeof SitemapRoute
  MinistriesCampusRoute: typeof MinistriesCampusRoute
  MinistriesMyaRoute: typeof MinistriesMyaRoute
  MinistriesMyfRoute: typeof MinistriesMyfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sermons': {
      id: '/sermons'
      path: '/sermons'
      fullPath: '/sermons'
      preLoaderRoute: typeof SermonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salvation': {
      id: '/salvation'
      path: '/salvation'
      fullPath: '/salvation'
      preLoaderRoute: typeof SalvationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camps': {
      id: '/camps'
      path: '/camps'
      fullPath: '/camps'
      preLoaderRoute: typeof CampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/README': {
      id: '/README'
      path: '/README'
      fullPath: '/README'
      preLoaderRoute: typeof READMERouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries/myf': {
      id: '/ministries/myf'
      path: '/ministries/myf'
      fullPath: '/ministries/myf'
      preLoaderRoute: typeof MinistriesMyfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries/mya': {
      id: '/ministries/mya'
      path: '/ministries/mya'
      fullPath: '/ministries/mya'
      preLoaderRoute: typeof MinistriesMyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries/campus': {
      id: '/ministries/campus'
      path: '/ministries/campus'
      fullPath: '/ministries/campus'
      preLoaderRoute: typeof MinistriesCampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/': {
      id: '/sitemap/'
      path: '/sitemap'
      fullPath: '/sitemap/'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  READMERoute: READMERoute,
  AboutRoute: AboutRoute,
  CampsRoute: CampsRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  MediaRoute: MediaRoute,
  PrayerRoute: PrayerRoute,
  SalvationRoute: SalvationRoute,
  SermonsRoute: SermonsRoute,
  StoriesRoute: StoriesRoute,
  VisitRoute: VisitRoute,
  SitemapRoute: SitemapRoute,
  MinistriesCampusRoute: MinistriesCampusRoute,
  MinistriesMyaRoute: MinistriesMyaRoute,
  MinistriesMyfRoute: MinistriesMyfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
